import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Activity, Brain, TrendingUp, Heart, Zap, Star } from 'lucide-react'

const Landing = () => {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Plans',
      description: 'Personalized 7-day workout and nutrition plans generated by advanced AI',
    },
    {
      icon: Activity,
      title: 'Smart Workouts',
      description: 'Dynamic exercise routines with video tutorials and real-time tracking',
    },
    {
      icon: Heart,
      title: 'AROMI AI Coach',
      description: 'Your 24/7 AI fitness assistant for guidance and motivation',
    },
    {
      icon: TrendingUp,
      title: 'Progress Analytics',
      description: 'Track your journey with detailed charts and insights',
    },
    {
      icon: Zap,
      title: 'Google Calendar',
      description: 'Sync workouts automatically to stay organized',
    },
    {
      icon: Star,
      title: 'Gamification',
      description: 'Earn achievements and contribute to charity with every calorie',
    },
  ]

  return (
    <div className="min-h-screen bg-white dark:bg-dark-bg">
      {/* Hero Section */}
      <section className="relative overflow-hidden gradient-hero text-white">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PHBhdHRlcm4gaWQ9ImdyaWQiIHdpZHRoPSI2MCIgaGVpZ2h0PSI2MCIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHBhdGggZD0iTSAxMCAwIEwgMCAwIDAgMTAiIGZpbGw9Im5vbmUiIHN0cm9rZT0id2hpdGUiIHN0cm9rZS13aWR0aD0iMSIvPjwvcGF0dGVybj48L2RlZnM+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0idXJsKCNncmlkKSIvPjwvc3ZnPg==')]"></div>
        </div>
        
        <div className="relative container mx-auto px-4 py-24">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center max-w-4xl mx-auto"
          >
            <h1 className="text-5xl md:text-7xl font-bold mb-6">
              Transform Your Fitness Journey with AI
            </h1>
            <p className="text-xl md:text-2xl mb-8 opacity-90">
              Personalized workouts, nutrition plans, and 24/7 AI coaching
              <br />
              designed just for you
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link to="/register" className="btn btn-lg bg-white text-primary-600 hover:bg-gray-100 px-8 py-4 text-lg">
                Get Started Free
              </Link>
              <Link to="/login" className="btn btn-lg border-2 border-white hover:bg-white/10 px-8 py-4 text-lg">
                Sign In
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50 dark:bg-dark-bg">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Everything You Need to Succeed
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-400">
              Powered by cutting-edge AI technology
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: idx * 0.1 }}
                viewport={{ once: true }}
                className="card card-hover p-6"
              >
                <div className="w-12 h-12 gradient-primary rounded-lg flex items-center justify-center text-white mb-4">
                  <feature.icon size={24} />
                </div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-gray-600 dark:text-gray-400">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-white dark:bg-dark-card">
        <div className="container mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Ready to Transform?
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-400 mb-8">
              Join thousands on their fitness journey
            </p>
            <Link to="/register" className="btn-primary btn-lg px-12 py-4 text-lg">
              Start Your Journey Today
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 bg-gray-900 text-white text-center">
        <p>&copy; 2026 Transformers. All rights reserved.</p>
      </footer>
    </div>
  )
}

export default Landing
